[package]
name = "waygate-test"
version.workspace = true
authors.workspace = true
description.workspace = true
license-file.workspace = true
edition.workspace = true

[dependencies]
waygate.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true